CREATE TABLE stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL,
  movement_type VARCHAR(32) NOT NULL,
  on_hand_delta BIGINT NOT NULL,
  reserved_delta BIGINT NOT NULL,
  on_hand_after BIGINT NOT NULL,
  reserved_after BIGINT NOT NULL,
  occurred_at TIMESTAMP NOT NULL,
  CONSTRAINT pk_stock_movements PRIMARY KEY (id),
  CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT ck_stock_movements_type CHECK (
    CASE
      WHEN movement_type = 'RECEIPT' THEN 1
      WHEN movement_type = 'RESERVATION' THEN 1
      WHEN movement_type = 'SHIPMENT' THEN 1
      WHEN movement_type = 'RESERVATION_RELEASE' THEN 1
      ELSE 0
    END = 1
  ),
  CONSTRAINT ck_stock_movements_non_zero_delta CHECK (
    on_hand_delta <> 0 OR reserved_delta <> 0
  ),
  CONSTRAINT ck_stock_movements_on_hand_after_non_negative CHECK (on_hand_after >= 0),
  CONSTRAINT ck_stock_movements_reserved_after_non_negative CHECK (reserved_after >= 0),
  CONSTRAINT ck_stock_movements_reserved_not_greater_than_on_hand
    CHECK (reserved_after <= on_hand_after)
);

CREATE INDEX ix_stock_movements_product_occurred
  ON stock_movements (product_id, occurred_at DESC, id DESC);

CREATE INDEX ix_stock_movements_type_occurred
  ON stock_movements (movement_type, occurred_at DESC, id DESC);
